import { callPython } from "@/lib/python-bridge";

export const dynamic = "force-dynamic";

// GET /api/bots/:id/embed.js -> JS widget loader generated by py_backend.services
export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  const host = req.headers.get("host") || "localhost:3000";
  const proto = host.startsWith("localhost") || host.startsWith("127.0.0.1") ? "http" : "https";

  const result = await callPython("embed_script", {
    botId: id,
    baseUrl: `${proto}://${host}`,
  });

  const script =
    typeof result.script === "string"
      ? result.script
      : `/* SiteMind AI: ${result.error ?? "unable to build widget"} */`;

  return new Response(script, {
    status: result.success ? 200 : 404,
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "public, max-age=60",
    },
  });
}
